### ISSUE TITLE
Proposal: integration with impress.js

### ISSUE THREAD

**Issue by OrangeX4** [touying-typ/touying#1]
@ntjess thanks for your transparent cover in https://github.com/andreasKroepelin/polylux/pull/91 and `fit-to-with` in https://github.com/andreasKroepelin/polylux/pull/96, they are elegant :-)

![8d20afe13805b376e32d76e18fc187fa](https://github.com/touying-typ/touying/assets/34951714/d61564a1-8400-48af-b5e7-d64655eee4cd)

![f21283fe76e0797942159d0e310d01a1](https://github.com/touying-typ/touying/assets/34951714/8df87f4e-f70c-476c-a5c9-2cc66c4e95f8)

I am very interested in using touying to achieve integration with impress.js. Perhaps it can also work together with https://github.com/andreasKroepelin/polylux/pull/123 and the typst-preview extension.

If you are willing, I can invite you to join the touying-typ organization as a maintainer :-)

**Comment by OrangeX4** [comment]
https://github.com/andreasKroepelin/polylux/issues/122

**Comment by ntjess** [comment]
@OrangeX4 I've finally had time to try out Touying in-depth. Well done!

I am interested in helping to maintain the library, and have a few ideas about impress.js support, but I won't have time to dedicate for a week or two.

**Comment by OrangeX4** [comment]
Thank you! I will initiate an invitation.

About the integration of impress.js, I don't think it's urgent; we can implement it later after considering it thoroughly. Also, I've been a bit busy lately and don't have much time to dedicate to it either.
