### ISSUE TITLE
How does one use a global command to center the title of each slide?

### ISSUE THREAD

**Issue by MooersLab** [touying-typ/touying#101]

**Comment by OrangeX4** [comment]
You can configure the header parameters in the theme function.

**Comment by MooersLab** [comment]
I am using the university theme. The documentation claims that the register function takes the header as an argument. What would the syntax be for centering the header?

**Comment by OrangeX4** [comment]
```typst
#show: university-theme.with(
  header-right: none,
  header: h(1fr) + utils.display-current-heading(level: 2) + h(1fr),
)
```

**Comment by MooersLab** [comment]
@OrangeX4 Works perfectly! Thank you! My attempts were way off the mark.
