### ISSUE TITLE
slide title bug: expected content, found function

### ISSUE THREAD

**Issue by lijunqiao2017** [touying-typ/touying#104]
```typst
#import "@preview/touying:0.5.3": *
#import themes.metropolis: *

#import "@preview/numbly:0.1.0": numbly

#show: metropolis-theme.with(
  aspect-ratio: "16-9",
  footer: self => self.info.institution,
  config-info(
    title: [VENT],
    subtitle: [],
    author: [L],
    date: datetime.today(),
    institution: [],
    logo: emoji.city,
  ),
)

#set page(
  margin: (x: 4em, y: 2em),
  header: align(top)[Header],
  footer: align(bottom)[Footer],
  header-ascent: 0em,
  footer-descent: 0em,
)

#set heading(numbering: numbly("{1}.", default: "1.1"))

#title-slide()

= 一级标题
== 二级标题
#slide(title: "希望的标题")[
  啊
]
```

控制台问题提示expected content, found function

**Comment by OrangeX4** [comment]
0.5.3 没有 title 参数，可以直接用 `== 标题`



---Original---
From: ***@***.***&gt;
Date: Mon, Oct 28, 2024 11:41 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [touying-typ/touying] slide title bug: expected content, foundfunction (Issue #104)




 #import ***@***.***/touying:0.5.3": * #import themes.metropolis: * #import ***@***.***/numbly:0.1.0": numbly #show: metropolis-theme.with(   aspect-ratio: "16-9",   footer: self =&gt; self.info.institution,   config-info(     title: [VENT],     subtitle: [],     author: [L],     date: datetime.today(),     institution: [],     logo: emoji.city,   ), ) #set page(   margin: (x: 4em, y: 2em),   header: align(top)[Header],   footer: align(bottom)[Footer],   header-ascent: 0em,   footer-descent: 0em, ) #set heading(numbering: numbly("{1}.", default: "1.1")) #title-slide() = 一级标题 == 二级标题 #slide(title: "希望的标题")[   啊 ]
 
控制台问题提示expected content, found function
