### ISSUE TITLE
Section/Subsection Heading Footnotes Duplicated

### ISSUE THREAD

**Issue by spidersouris** [touying-typ/touying#110]
### Description of Issue

Defining a footnote on a section/subsection heading (level 1 or 2) duplicates it.

### Minimal Example

```typst
#import "@preview/touying:0.5.2": *
#import themes.simple: *

#show: simple-theme.with(aspect-ratio: "16-9")
#show heading: it => text(fill: red, smallcaps(it))

= Title#footnote("this is a duplicated footnote")

== First Slide#footnote("this is another duplicated footnote")

=== 123#footnote("this footnote is fine though")

Hello, Touying!

Hello, Typst!
```

### Current Behavior

It seems that footnotes are applied once to the section/subsection title (in the header) and once to the slide title? The screenshot below shows that footnote 1 first appears on page 2 next to the "First Slide" section title, and a second identical footnote (numbered 2) appears on the very first slide next to "Title".

![image](https://github.com/user-attachments/assets/ae44b37f-f0e0-4419-86b9-dbf3e1f76f12)

**Comment by OrangeX4** [comment]
There is currently no good solution for this, but try not to use footnote in the heading.
