### ISSUE TITLE
Showing previous heading and current heading in header

### ISSUE THREAD

**Issue by tigerros** [touying-typ/touying#113]
I want to make a theme that displays the last heading, then the current heading. If the current heading is top level, it only displays that. I could do this by just having an array `sections` that I pass into each slide function, but I was wondering if there is a better way to do it.

Example:

```typst
= Foo
Lorem
== Bar
ipsum
=== Baz
dolor
== Qux
sit
```

Would show:

```md
# slide 1
header: Foo
body: Lorem
# slide 2
header: Foo -> Bar
body: ipsum
# slide 3
header: Bar -> Baz
body: dolor
# slide 4
header: Foo -> Qux
body: sit
```

**Comment by OrangeX4** [comment]
I think you might just need to understand the usage of [query(heading)](https://typst.app/docs/reference/introspection/query/) in typst, which doesn't conflict with touying.
