### ISSUE TITLE
我可以在outline中隐藏页码吗？

### ISSUE THREAD

**Issue by Quaternijkon** [touying-typ/touying#117]
我想在结尾列出本次报告所展示的全部内容，但跟随在后面的页码有点烦人，我发现outline中没有参数用于设置页码样式。

**Comment by OrangeX4** [comment]
https://github.com/touying-typ/touying/issues/81

**Comment by Quaternijkon** [comment]
> #81

thanks, 但是如果我只是希望在最后一页的回顾上隐藏页码，之前的outline不隐藏。我目前的方法是在最后的slide前面添加
```
#show outline.entry: it => {
  it.body
}
```
但是这种操作违背了内容和样式分离的原则，请问是否可能在样式的设置放在theme.typ中的end-slide()函数中呢？（类似focus-slide()）
谢谢！

**Comment by OrangeX4** [comment]
那就重写 end-slide 函数



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月17日(周日) 上午10:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [touying-typ/touying] 我可以在outline中隐藏页码吗？ (Issue #117)




  
#81
  
thanks, 但是如果我只是希望在最后一页的回顾上隐藏页码，之前的outline不隐藏。我目前的方法是在最后的slide前面添加
 #show outline.entry: it =&gt; {   it.body }  
但是这种操作违背了内容和样式分离的原则，请问是否可能在样式的设置放在theme.typ中的end-slide()函数中呢？（类似focus-slide()）
 谢谢！
