### ISSUE TITLE
Exported SVG does not show the title page as expected

### ISSUE THREAD

**Issue by photino** [touying-typ/touying#119]
Exported PDF works as expected, but exported SVG does not show the title page.

[touying.svg](https://github.com/user-attachments/assets/2c7aa0b3-5c79-475a-8078-eb10340218bd)

**Comment by OrangeX4** [comment]
What is the SVG export tool you use? Do you have set pdfpc.config()?



---Original---
From: "Zan ***@***.***&gt;
Date: Wed, Nov 20, 2024 13:28 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [touying-typ/touying] Exported SVG does not show the title page(Issue #119)




 
Exported PDF works as expected, but exported SVG does not show the title page.
 
touying.svg (view on web)

**Comment by photino** [comment]
> What is the SVG export tool you use? Do you have set pdfpc.config()?

I use the method https://docs.rs/typst-svg/latest/typst_svg/fn.svg_merged.html to export the SVG.

**Comment by photino** [comment]
If I only have a simple title page

```typst
#import "@preview/touying:0.5.3": *
#import themes.simple: *

#show: simple-theme.with(aspect-ratio: "16-9")

= Title
```
It exports a SVG as expected.

**Comment by photino** [comment]
If I add a slide page

```typst
#import "@preview/touying:0.5.3": *
#import themes.simple: *

#show: simple-theme.with(aspect-ratio: "16-9")

= Title

== First Slide

Hello, Touying!
```
The title page does not show as expected:
![slides](https://github.com/user-attachments/assets/3be8cb32-16aa-4618-a960-c9fcd74fe0bc)

**Comment by photino** [comment]
The generated SVG has repeated code:

```svg
    <path class="typst-shape" fill="#ffffff" fill-rule="nonzero" d="M 0 0 L 0 473.563 L 841.8898 473.563 L 841.8898 0 Z "/>
```
If I removed the second one, then the svg works as expected 😄

**Comment by photino** [comment]
How can we set the slide background as `transparent`?

**Comment by photino** [comment]
See also 
- [Support transparent page fill](https://github.com/typst/typst/pull/4586)
- [Incorrect filling of svg (v12.0.0)](https://github.com/typst/typst/issues/5400)

**Comment by Myriad-Dreamin** [comment]
touying's doc examples was also not rendered by typst-svg correctly. I fixed it for all doc examples by set page to `none` fill:

```typ
#set page(fill: none)
```

https://github.com/Myriad-Dreamin/tinymist/blob/27816e421f8666441c46df66312c23d671875989/crates/typlite/src/lib.rs#L442
