### ISSUE TITLE
Page Columns feature

### ISSUE THREAD

**Issue by lidabaoo** [touying-typ/touying#17]
使用 `#slide[..][..]` 时，有什么方法可以终止当前slide的多列布局回到单列模式？

具体来说，例如 
```
#slide(composer: utils.side-by-side.with(columns: (1fr, 1fr,1fr), gutter: 1em)[
  #rect(height:100%,width:100%,[First column.#linebreak() Part I])
],[
  #rect(height:100%,width:100%,[second column.#linebreak() Part II])
],[
  #rect(height:100%,width:100%,[third column.#linebreak() Part II])
])
```
其结果如下
![Snipaste_2024-03-20_21-04-41](https://github.com/touying-typ/touying/assets/69191820/87e6ea86-6451-4330-ab64-fa0783c36e31)

有的时候可能需要，对这张slide 进行总结，这时候如何终止多列的特性，实现红色部分的内容添加？touying 有专门的语法选项控制吗？还是可以通过其他 typst 特性去实现呢? 

我尝试使用 `#place(...[summary...])` 或者 `#box(width:300%,...[sumary...])` ，试图让文本超过第一列的范围，但是结果都不理想。

**Comment by OrangeX4** [comment]
你可以直接在 slide[] 里面用 grid 函数，grid 布局起来很方便。



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 20, 2024 21:36 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [touying-typ/touying] Page Columns feature (Issue #17)




 
使用 #slide[..][..] 时，有什么方法可以终止当前slide的多列布局回到单列模式？
 
具体来说，例如
 #slide(composer: utils.side-by-side.with(columns: (1fr, 1fr,1fr), gutter: 1em)[   #rect(height:100%,width:100%,[First column.#linebreak() Part I]) ],[   #rect(height:100%,width:100%,[second column.#linebreak() Part II]) ],[   #rect(height:100%,width:100%,[third column.#linebreak() Part II]) ])  
其结果如下
 Snipaste_2024-03-20_21-04-41.png (view on web)
 
有的时候可能需要，对这张slide 进行总结，这时候如何终止多列的特性，实现红色部分的内容添加？touying 有专门的语法选项控制吗？还是可以通过其他 typst 特性去实现呢?
 
我尝试使用 #place(...[summary...]) 或者 #box(width:300%,...[sumary...]) ，试图让文本超过第一列的范围，但是结果都不理想。

**Comment by lidabaoo** [comment]
> 你可以直接在 slide[] 里面用 grid 函数，grid 布局起来很方便。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Wed, Mar 20, 2024 21:36 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [touying-typ/touying] Page Columns feature (Issue #17) 使用 #slide[..][..] 时，有什么方法可以终止当前slide的多列布局回到单列模式？ 具体来说，例如 #slide(composer: utils.side-by-side.with(columns: (1fr, 1fr,1fr), gutter: 1em)[ #rect(height:100%,width:100%,[First column.#linebreak() Part I]) ],[ #rect(height:100%,width:100%,[second column.#linebreak() Part II]) ],[ #rect(height:100%,width:100%,[third column.#linebreak() Part II]) ]) 其结果如下 Snipaste_2024-03-20_21-04-41.png (view on web) 有的时候可能需要，对这张slide 进行总结，这时候如何终止多列的特性，实现红色部分的内容添加？touying 有专门的语法选项控制吗？还是可以通过其他 typst 特性去实现呢? 我尝试使用 #place(...[summary...]) 或者 #box(width:300%,...[sumary...]) ，试图让文本超过第一列的范围，但是结果都不理想。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

OK 完美解决，我以为`gird` 中不能使用 `only, uncover`，一直没留意这个函数。后面仔细看了说明文档只是不能使用 `pause` 和 `meanwhile`。
