### ISSUE TITLE
Weird behavior of outline slide

### ISSUE THREAD

**Issue by s92077** [touying-typ/touying#23]
In the current version (version 0.3.3) of dewdrop theme, if there are too many sections to be packed into a single outline slide, it seem that each of the slide of the outline create a new section/subsection, which is not desired. Is there any quick fix to that?

**Comment by OrangeX4** [comment]
Can you provide a concrete example?

**Comment by s92077** [comment]
For example, in the following code, each section is repeated four times in the outline.
```typst
#import "@preview/touying:0.3.3": *

#let s = themes.dewdrop.register(
  aspect-ratio: "16-9",
  footer: [Dewdrop],
  navigation: "mini-slides",
)
#let s = (s.methods.info)(
  self: s,
  title: [Title],
  subtitle: [Subtitle],
  author: [Authors],
  date: datetime.today(),
  institution: [Institution],
)
#let (init, slides, touying-outline, alert) = utils.methods(s)
#show: init

#show strong: alert

#let (slide, empty-slide, title-slide, new-section-slide, focus-slide) = utils.slides(s)
#show: slides

= 1
= 2
= 3
= 4
= 5
= 6
= 7
= 8
= 9
= 10
= 11
```

**Comment by OrangeX4** [comment]
It's really a bug, but not a bug with outline slide. If you want an outline slide that doesn't create new sections, you can

```typst
#slide[
  #touying-outline()
]
```

The bug here is that a multi-page slide creates the same section multiple times.
