### ISSUE TITLE
The description for touying-aqua on Universe should reflect that it is a theme for touying

### ISSUE THREAD

**Issue by Enivex** [touying-typ/touying#25]
Currently they appear more or less identically, except for their title and thumbnail.

![image](https://github.com/touying-typ/touying/assets/2191754/c1a01704-f83b-4fac-b9b0-3a6db605a9df)

![image](https://github.com/touying-typ/touying/assets/2191754/5dfd2d28-3dfe-4061-92ff-47a30cd8827c)

**Comment by OrangeX4** [comment]
Thanks, I'll update the description of `touying-aqua` in the next release.

**Comment by OrangeX4** [comment]
Done in 0.4.0
