### ISSUE TITLE
`fletcher-diagram` does not work in other elements

### ISSUE THREAD

**Issue by yjcui** [touying-typ/touying#34]
It is a great feature integrating `fletcher` into Touying. One issue I noticed is, I can not use `fletcher-diagram` in other elements like `grid` or `columns` as it will display as blank. This would be a critical feature as it's common to have text on left side while some chart on the right half in presentation, if one wants to use `fletcher` generated diagrams.

Below is the code snippet for testing. Only the left column is visible in the compiled pdf.

```
#slide[
  #grid(columns: (1fr, 1fr), gutter: 0.5em, [
    - Item 1
    - Item 2
  ], [#fletcher-diagram(cell-size: 15mm, $
      G edge(f, ->) edge("d", pi, ->>) & im(f) \
      G slash ker(f) edge("ur", tilde(f), "hook-->")
    $)
  ])
]
```

**Comment by OrangeX4** [comment]
try

```typst
#slide[
    - Item 1
    - Item 2
][
    #fletcher-diagram(cell-size: 15mm, $
      G edge(f, ->) edge("d", pi, ->>) & im(f) \
      G slash ker(f) edge("ur", tilde(f), "hook-->")
    $)
]
```

https://touying-typ.github.io/touying/docs/layout#page-columns

**Comment by yjcui** [comment]
It works! Thanks!

**Comment by yjcui** [comment]
It works! Thanks!
