### ISSUE TITLE
Empty #`pause` breaks page dimension

### ISSUE THREAD

**Issue by Enter-tainer** [touying-typ/touying#35]
```
#import "@preview/touying:0.4.0": *

#let s = themes.simple.register(aspect-ratio: "16-9", footer: [Simple slides])
#let s = (s.methods.enable-transparent-cover)(self: s)
#let (init, slides) = utils.methods(s)
#show: init

#let (slide, empty-slide, title-slide, centered-slide, focus-slide) = utils.slides(s)
#show: slides

= 第一章

#pause

= 第二章

```
![image](https://github.com/touying-typ/touying/assets/25521218/b39fd095-2157-4b01-971f-6e1884053876)

**Comment by OrangeX4** [comment]
It's weird, and few people will need to use it that way. I'll try to see if I can fix it, and if it's difficult I probably won't fix it.

**Comment by Enter-tainer** [comment]
> It's weird, and few people will need to use it that way. I'll try to see if I can fix it, and if it's difficult I probably won't fix it.

i understand your decision. i'm playing with touying and this appears during editing. it's harmless but looks interesting
