### ISSUE TITLE
Proposal: More customization to the title page

### ISSUE THREAD

**Issue by hecmas** [touying-typ/touying#36]
It would be nice to be able to add images/icons/graphics to the title page of some (if not all) themes. Also, It would be nice to customize font sizes through a parameter. In general, I think more customization to the title slide is needed.

As an example, this is the best I could do with the metropolis theme:
<img width="1117" alt="Captura de pantalla 2024-04-22 a las 10 57 14" src="https://github.com/touying-typ/touying/assets/68732820/6e46b223-a767-4140-b541-f4ddb8b0214d">

But I would love to be able to do something like this:
<img width="1044" alt="Captura de pantalla 2024-04-22 a las 10 53 05" src="https://github.com/touying-typ/touying/assets/68732820/b4c01270-ec77-4912-8781-d7d0f5ed3903">

**Comment by OrangeX4** [comment]
You don't have to use touying's native title-slide, you can start with empty-slide and write your own. Of course, I'll strengthen the ability to customize later, but it shouldn't be very satisfying for everyone.
