### ISSUE TITLE
Proposal: Alternative new section slide

### ISSUE THREAD

**Issue by hecmas** [touying-typ/touying#37]
Currently, the new section slide is the default one that comes with metropolis. It would be nice to have alternatives, and in general be able to easily customize your own.

As an example, I'd prefer something using the covering features:
<img width="1048" alt="Captura de pantalla 2024-04-22 a las 11 00 30" src="https://github.com/touying-typ/touying/assets/68732820/64a5b861-e26f-4bdd-9a20-1cea913260f5">

**Comment by OrangeX4** [comment]
Of course you can customize the new section slide yourself, refer to the documentation https://touying-typ.github.io/touying/docs/code-styles#convention-over-configuration

**Comment by OrangeX4** [comment]
I'll close this issue and feel free to reopen it if you still have any doubts :-)
