### ISSUE TITLE
Equation numbering increases with `#pause` on each subslide

### ISSUE THREAD

**Issue by yjcui** [touying-typ/touying#38]
When subslide is used (with `#pause`, `#only`, etc.), numbering of equation keeps increasing on each subslide, where they should remain the same number.

Code snippet for testing.
```
#set math.equation(numbering: "(1)")

#slide[
  - Item 1
  #pause
  - Item 2
  #pause
  - Item 3
  
  $ alpha + beta = f(x) $
]
```

**Comment by OrangeX4** [comment]
This is a known issue and difficult to fix in touying right now, which will need to wait until typst implements frozen state to deal with this.
https://laurmaedje.github.io/posts/frozen-state/
