### ISSUE TITLE
Weird behavior of touying-outline in theme "metropolis" with slide-level 2

### ISSUE THREAD

**Issue by ShampooDeng** [touying-typ/touying#40]
**Description**
Level3 heading gets seperated into a new slide when slide-level is set to 2 globally in theme "metropolis".
And level1 heading and level3 heading are assigned to the header of subsection slide(level2 heading content) and subsubsection slide(level3 heading content) respectively.
This phenomenon is shown in the screenshot at the bottom.

**Reproduce**
typst version: 0.11.0 (2bf9f95d)
touying version: 0.4.0
The following script will reporoduce this issue.

```typst
// I just copyed the temple of touying-aqua, and made modifications to it
#let s = themes.metropolis.register(aspect-ratio: "16-9")
//...
#show: slides.with(
  outline-title: [outline],
  slide-level: 2,
)

= section

== subsection

TODO

=== subsubsection

TODO
```

**Expected behavior**
Outline presents a table of content with a depth to level 2 heading. 
And level 2 heading gets placed in the slide header, while level 3 heading is in the body of the slide.
It should be look like the image below.
![image](https://github.com/touying-typ/touying/assets/30762004/0f6bd94f-c365-4195-88df-e232af06d2aa)

**Screenshot**
![image](https://github.com/touying-typ/touying/assets/30762004/4ac7517d-7131-4cb2-b48c-462055deb03d)

**Comment by ShampooDeng** [comment]
Setting the slide-level to 1 gets exactlly what I want, except the outline only presents level 1 heading. I'm not sure if it's bug, or it's designed in this way 🤔 .

**Comment by OrangeX4** [comment]
This is the expected behavior, currently touying has no subsubsection, your subsubsection is just a title, currently metropolis displays title first, then the current section, by default subsection is not considered.
