### ISSUE TITLE
Metropolis theme: Decoupling text fill color and primary dark color?

### ISSUE THREAD

**Issue by JKRhb** [touying-typ/touying#45]
First of all, thank you for the great package :)

I am currently using the Metropolis theme for creating presentation slides and was considering changing the color theme. However, in the case of the primary dark color, doing so is not really possible since this also changes the text color on the slides:

<img width="858" alt="image" src="https://github.com/touying-typ/touying/assets/12641361/d32ae4f0-e373-4bbd-84e6-8b3b7e65f436">

Would it be possible to decouple the text color from the color that is being used for the general slide layout, or provide other means for configuration here?

**Comment by OrangeX4** [comment]
Sorry, I didn't think about this case, I'll find a way to fix it in the next version, for now you can use

```typst
#(s.methods.slide = s.methods.slide.with(setting: body => text(fill: black, body)))
```

to change the text color.

**Comment by JKRhb** [comment]
Thank you for your quick answer and the workaround :)
