### ISSUE TITLE
How to center text horizontally?

### ISSUE THREAD

**Issue by Wongboo** [touying-typ/touying#47]
`touying`
<img width="843" alt="截屏2024-05-30 12 12 34" src="https://github.com/touying-typ/touying/assets/44860323/bfb0f51f-330e-4b45-955e-63f1257b5fa0">
`beamer`
<img width="950" alt="截屏2024-05-30 12 12 28" src="https://github.com/touying-typ/touying/assets/44860323/7c7dfafe-ca6a-4d47-8412-347b7cc98964">

**Comment by Wongboo** [comment]
BTW, it seems that `touying` is wider than `beamer`, how to fix it?

**Comment by OrangeX4** [comment]
1. `#align(horizon)[...]`
2. `aspect-ratio: "4-3"`

**Comment by Wongboo** [comment]
> 1. `#align(horizon)[...]`
> 
> 2. `aspect-ratio: "4-3"`

What if I want to align automatically for every slide
?

**Comment by OrangeX4** [comment]
#(s.methods.slide = s.methods.slide.with(setting: align.with(horizon)))



---Original---
From: ***@***.***&gt;
Date: Thu, May 30, 2024 12:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [touying-typ/touying] How to center text horizontally? (Issue#47)




   
 
#align(horizon)[...]
 
 
 
aspect-ratio: "4-3"
 
   
What if I want to align automatically for every slide
 ?

**Comment by Wongboo** [comment]
Thanks sincerely!
