### ISSUE TITLE
How to remove the numbering of subsections in the Dewdrop Theme?

### ISSUE THREAD

**Issue by OB0NE** [touying-typ/touying#48]
I tried the [example](https://touying-typ.github.io/touying/docs/themes/dewdrop#example) of the Dewdrop Theme in the Typst app but got a different appearance: 
![image](https://github.com/touying-typ/touying/assets/144986313/4dbd9b95-7f9e-4f84-bfd9-e82a95f4103b)
which contains unwanted numbering before subsection titles. And I want to achieve what the example picture looks like:
![image](https://github.com/touying-typ/touying/assets/144986313/4ce95a32-0a68-4a3c-ba21-328b1e1047ff)
I have tried to remove the numbering by :
`#let s = (s.methods.numbering)(self: s, section: none, none)`
but failed. 
So, I wanted to know if there is a way to remove the unwanted numbering before headings in the theme dewdrop.

**Comment by OrangeX4** [comment]
```typ
#(s.numbering = none)
```

I will fix `s.methods.numbering` in the next release.

**Comment by OB0NE** [comment]
It works. Thanks a lot!

> ```typst
> #(s.numbering = none)
> ```
> 
> I will fix `s.methods.numbering` in the next release.
