### ISSUE TITLE
HTML export based on web version Typst

### ISSUE THREAD

**Issue by jackyliu16** [touying-typ/touying#49]
First of all, thank you for your excellent work. I have a very strange request. That is, the ppt file I want to make needs to be shared within the group, so that they can jointly modify this file, which seems to be a more convenient option to use the web version at present (God knows why they won't git) However, it seems that direct playback or export support is not yet available in the web version. Do you have any recommended solutions? (I also tried some other things like slidev, but either you need to compile locally or you need to open the server locally, or gh-page[classroom may not open in some country]) 

--- ORGINAL CN
首先感谢你优秀的作品，我有一个很奇怪的需求
就是我想要制作的ppt文件需要在组内分享，让他们可以共同修改这个文件，这目前看来使用网页版本是比较方便的选项
（鬼知道为什么他们不会git）
但是现在的情况是似乎typst网页版本中尚未实现直接播放或者导出的支持，你有什么推荐的解决方案吗？
（我还尝试了一些其他比如说slidev的，但是要不是需要在本地编译要不就是需要在本地打开服务器，或者是gh-page[教室不一定能打开]）

**Comment by OrangeX4** [comment]
If you are using the official Typst WebApp, they do have plans to add a presentation mode feature in the future, but it is not available yet. Additionally, you need to subscribe to Typst Pro to use it.

Currently, I recommend using the WebApp to edit your document, then export it as a PDF for local presentation, or download a backup to your local machine and use Touying Exporter to export it as HTML for deployment.

--- ORGINAL CN
如果你指的是 Typst 官方的 WebApp，后续他们是有计划添加 presentation mode 的放映功能的，不过目前还没有，以及需要付费成为 Typst Pro 才能使用。目前我推荐你可以使用 Web App 编辑，然后选择导出 PDF，再本地播放 PDF，或者 Backup 下载到本地，然后使用 Touying Exporter 导出为 HTML 来部署。

**Comment by OrangeX4** [comment]
Because webapp has added the slide show feature for typst pro users, close this issue.
