### ISSUE TITLE
bad slide layout when content is none

### ISSUE THREAD

**Issue by QuadnucYard** [touying-typ/touying#50]
Use the `Quick start` example, and add a slide with content set to `{}` (or `none`)

```typ
#import "@preview/touying:0.4.2": *

#let s = themes.simple.register(aspect-ratio: "16-9")
#let (init, slides) = utils.methods(s)
#show: init

#let (slide, empty-slide) = utils.slides(s)
#show: slides

= Title

#slide(self => (self.methods.touying-slide)(self: self, repeat: none, section: (title: [Contents]), {}))

== First Slide

Hello, Touying!
```

This will yield:

![image](https://github.com/touying-typ/touying/assets/50077758/f2cf2f0a-aaf5-4540-a340-90f5af322383)

If we put the slide at the end:

```typ
= Title

== First Slide

Hello, Touying!

#slide(self => (self.methods.touying-slide)(self: self, repeat: none, section: (title: [Contents]), {}))
```

![image](https://github.com/touying-typ/touying/assets/50077758/32e45426-94b7-4398-95ba-8e0d0ff254d8)

**Comment by Enter-tainer** [comment]
I believe this is related #35
