### ISSUE TITLE
Unable to use `square`

### ISSUE THREAD

**Issue by YDX-2147483647** [touying-typ/touying#73]
[The `square` Function](https://typst.app/docs/reference/visualize/square/) draws a square with optional content. It might have no `body`, making touying broken.

```typst
#import "@preview/touying:0.5.2": themes
#import themes.simple: simple-theme

#show: simple-theme.with(aspect-ratio: "16-9")

#square()
```

```log
error: content does not contain field "body"
     ┌─ @preview/touying:0.5.2\src\core.typ:1124:16
     │
1124 │           child.body,
     │                 ^^^^
```

https://github.com/touying-typ/touying/blob/334f8a2190ae1767c269b75474c7d33f0aa8f0bc/src/core.typ#L1119-L1125

**Comment by YDX-2147483647** [comment]
## Workaround

Give an invisible `body`: `#square("")`.

Caveat: The square expands to fit this content, and no longer takes on the default `30pt`.

**Comment by OrangeX4** [comment]
Thanks! This is indeed a bug. You can bypass it for now by using `#context square()`
