### ISSUE TITLE
Update cetz usage with only and uncover

### ISSUE THREAD

**Issue by mohe2015** [touying-typ/touying#74]
Hi,

it seems that the cetz only and uncover example at https://touying-typ.github.io/docs/next/integration/cetz#only-and-uncover is outdated. How would I do this with the current version?

**Comment by mohe2015** [comment]
Seems like
```typ
self = utils.merge-dicts(
  self,
  config-methods(cover: utils.method-wrapper(hide.with(bounds: true))),
)
let (uncover,only) = utils.methods(self) 
```
actually does the job

**Comment by OrangeX4** [comment]
Thanks! I have fixed it.
