### ISSUE TITLE
Section, subsections and slide title as header level

### ISSUE THREAD

**Issue by fbob** [touying-typ/touying#8]
I know that we can use H1 and H2 header levels like this to organize a presentation : 

= Section
== Slide title

But is it possible to segment the presentation using  H1,H2 and H3 header levels like this : 

= Section
== Subsection
=== Slide title

It could make conversion from other format (I'm using obsidian+ pandoc export)  much easier.

**Comment by OrangeX4** [comment]
I think it's a good idea, and I'll consider adding it in the next release, thanks :-)
