### ISSUE TITLE
new-section-slide for theme stargazer keep untouched even modified the tile in outline-slide

### ISSUE THREAD

**Issue by jenningsloy318** [touying-typ/touying#80]
Hi colleages,
I found that in theme stargazer, the definition new-section-slide has some issue,
the title keep modified  even when outline-slide is changed
I modified the outline-slide
```
#outline-slide(title: "Agenda")
```
and the definition
```typ
#let new-section-slide(
  title: utils.i18n-outline-title,
  level: 1,
  numbered: true,
  ..args,
  body,
) = outline-slide(title: title, level: level, numbered: numbered, ..args)
```
the first outline is no issue 
![image](https://github.com/user-attachments/assets/3d34d8dd-fd6d-4247-b403-4c0464edfa04)
but the subsequent will have issue

![image](https://github.com/user-attachments/assets/1e016cef-4de0-4b65-8fee-32aaa840952d)

**Comment by OrangeX4** [comment]
Sorry I don't quite understand your question, can you provide a minimal reproducible example?

**Comment by jenningsloy318** [comment]
that is i add the outline slides with 
```
#outline-slide(title: "Agenda")
```
here I changed the title to "Agenda" which is not the default title "Outline"

so the it first appearance at second slide, it is change to "Agenda"

but in theme stargazer, at the beginning of each section, it will also display the outline, but with the current section highlighted, this time the titile is still "outline", not my midification "Agenda".

you can preproduce it via 
```typ
#import "@preview/touying:0.5.2": *
#import themes.stargazer: *

#show: stargazer-theme.with(
  // Lang and font configuration
  lang: "en",
  align: left + horizon,
  font: ("Source Han Sans SC", "Source Han Sans"),
  asaspect-ratio: "16-9",
  // Basic information
  config-info(
    title: [xxxx],
    subtitle: [xx],
    author: [xx],
    date: datetime.today(),
    institution: [xx],
  ),
)

#title-slide()

#outline-slide(title: "Agenda")

= first chapter

#lorem(10)


= second chapter

#lorem(10)

```

**Comment by OrangeX4** [comment]
You should use `config-common(new-section-slide-fn: new-section-slide.with(title: [Agenda]))`:

```typst
#import "@preview/touying:0.5.2": *
#import themes.stargazer: *

#show: stargazer-theme.with(
  // Lang and font configuration
  lang: "en",
  align: left + horizon,
  font: ("Source Han Sans SC", "Source Han Sans"),
  asaspect-ratio: "16-9",
  // Basic information
  config-info(
    title: [xxxx],
    subtitle: [xx],
    author: [xx],
    date: datetime.today(),
    institution: [xx],
  ),
  config-common(new-section-slide-fn: new-section-slide.with(title: [Agenda])),
)

#title-slide()

#outline-slide(title: [Agenda])

= first chapter

#lorem(10)


= second chapter

#lorem(10)
```
