### ISSUE TITLE
Subsection in `#slide[]` have wrong heading

### ISSUE THREAD

**Issue by Pamplemousse** [touying-typ/touying#84]
Creating a subsection under a `#slide[]` seems to give it an overly nested heading number.

The following minimal example code:
```typst
#import "@preview/touying:0.5.2": slide, themes
#import themes.metropolis: *

#show: metropolis-theme

#set heading(numbering: "1.")

= foo

#slide[
  == bar

  == baz
]
```

compiled with the following command:
```shell
typst watch --format png ./mwe.typ mwe{n}.png 
```

produces the following slides:

![mwe1](https://github.com/user-attachments/assets/7d9f49c7-cb53-43b1-a4e4-c399f5dc4499)
![mwe2](https://github.com/user-attachments/assets/95097f70-7180-4b14-8cdc-7a7e303844b2)

where we can see that the heading for `bar` and `baz` are `1.1.1.1.` and `1.1.1.2` respectively, while I expected `1.1` and `1.2`.

**Comment by OrangeX4** [comment]
`config-common(auto-offset-for-heading: false)`
