### ISSUE TITLE
how to stop slide counting?

### ISSUE THREAD

**Issue by rveltz** [touying-typ/touying#87]
Hi!

How can I stop the slide counter from a specific slide? (say)

Thank you

```
= Appendix
== Bibliography<touying:hidden>
// stop counting from here
```

**Comment by OrangeX4** [comment]
#show: appendix



---Original---
From: "Romain ***@***.***&gt;
Date: Sun, Sep 29, 2024 20:50 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [touying-typ/touying] how to stop slide counting? (Issue #87)




 
Hi!
 
How can I stop the slide counter from a specific slide? (say)
 
Thank you
 = Appendix == Bibliography<touying:hidden&gt; // stop counting from here

**Comment by rveltz** [comment]
It does not make any change:

```
...

#show: appendix

= Appendix//<touying:hidden>

Please pay attention to the current slide number.

==  Notes<touying:hidden>
bla

== Bibliography<touying:hidden>
#bibliography("hdr.bib", title: none, style: "apa")
```
```

**Comment by rveltz** [comment]
<img width="583" alt="Screenshot 2024-09-29 at 3 27 06 PM" src="https://github.com/user-attachments/assets/d2edffd3-c235-4ba0-8f67-90bec20d101e">

**Comment by OrangeX4** [comment]
Can you provide a minimally reproducible example?

**Comment by rveltz** [comment]
I sent you an email.

**Comment by OrangeX4** [comment]
I checked the email you sent and I think it worked correctly.

In touying, only last-slide-counter will be frozen, while slide-counter will not be frozen, which is expected.

Maybe you were confused by your own `#utils.slide-counter.update()`, I don't quite understand why you need to manually change slide-counter.

**Comment by rveltz** [comment]
Yes it worked well in the end
