### ISSUE TITLE
Hidden slide numbering when using `show-notes-on-second-screen: bottom`

### ISSUE THREAD

**Issue by CharlesAttend** [touying-typ/touying#89]
Hello,

Thank you for developing Touying! I created my internship defense slides using it, which allowed me to avoid LaTeX, Google Slides, and PowerPoint.

I've noticed that the slide numbering disappears when using `show-notes-on-second-screen: bottom`. I quickly checked the code but I'm not sure why this is happening.

Here is the minimal reproducible code:

```typst
#import "@preview/touying:0.5.2": *
#import themes.simple: *

#show: simple-theme.with(config-common(show-notes-on-second-screen: bottom))

= Title

== First Slide

Hello, Touying!

#pause

Hello, Typst!
```

Thank you for enabling slides creation in Typst!

**Comment by OrangeX4** [comment]
Thanks, fixed.

It will be released in version 0.5.3
