### ISSUE TITLE
`touying-fn-wrapper` is broken inside a `grid`

### ISSUE THREAD

**Issue by happycorsair** [touying-typ/touying#95]
Hello!

`touying-fn-wrapper` function doesn't work properly inside a `grid`.

A simple example:
```typst
#let testblock(body) = {
  touying-fn-wrapper((self: none) => {
    body
  })
}

#grid(
  columns: 2,
  text[aaa],
  testblock(
    [bbb],
  ),
)
#testblock(
  [ccc],
)
```
No problem with `aaa` or `ccc`, but `bbb` is not printed unless I remove `touying-fn-wrapper`.

PS: Thank you for a great job! Touying and typst are really great!

**Comment by OrangeX4** [comment]
Fixed in #82 .

It will be released in 0.5.3
