### ISSUE TITLE
Every second slide is blank when using pause and multiple page slides 

### ISSUE THREAD

**Issue by AlexD97** [touying-typ/touying#99]
When I use pause on slides that have too much text for one slide, every second slide is blank.

MWE:

```
#import "@preview/touying:0.5.3": *
#import themes.simple: *

#show: simple-theme.with(
    aspect-ratio: "16-9",
)

MWE:
#pause

Now,
#pause

there
#pause

are
#pause

blank
#pause

slides
#pause

in
#pause

between.
```

**Comment by OrangeX4** [comment]
This is because touying has no way of knowing how many slides these things have generated, just repeating them.

**Comment by OrangeX4** [comment]
You should add a `#pagebreak` by yourself.

**Comment by AlexD97** [comment]
Ah, I see. Thanks for the answer.
